# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pikvm < Formula
  desc "PiKVM ATX power control — terminal UI and CLI"
  homepage "https://github.com/j4y-w4lk3r/pikvm"
  version "0.3.0"
  license "MIT"

  depends_on "chafa" => :optional
  depends_on "ffmpeg" => :optional
  depends_on "fzf" => :optional
  depends_on "mpv" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.0/pikvm_0.3.0_darwin_x86_64.tar.gz"
      sha256 "794750579482b6d74a12c1b300cbe06252f7bd1952e552bdf009da7bdc612dab"

      define_method(:install) do
        bin.install "pikvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.0/pikvm_0.3.0_darwin_arm64.tar.gz"
      sha256 "8a2efbf9abea70bf0d59267a97e45a57461ba626292b3e5f4658d0508de783b5"

      define_method(:install) do
        bin.install "pikvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.0/pikvm_0.3.0_linux_x86_64.tar.gz"
      sha256 "62f8a94ebe1e89ff27300fb3534882febed8be67dec42fe0f98c2c3addf5ecb5"
      define_method(:install) do
        bin.install "pikvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.0/pikvm_0.3.0_linux_arm64.tar.gz"
      sha256 "c331662cfc9b4fcd54b5461c7c31433fa6d389273ca8188be099db7e2818be14"
      define_method(:install) do
        bin.install "pikvm"
      end
    end
  end

  test do
    assert_match "PiKVM Control", shell_output("#{bin}/pikvm --help")
  end
end
