# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pikvm < Formula
  desc "PiKVM ATX power control — terminal UI and CLI"
  homepage "https://github.com/j4y-w4lk3r/pikvm"
  version "0.3.5"
  license "MIT"

  depends_on "chafa" => :optional
  depends_on "ffmpeg" => :optional
  depends_on "fzf" => :optional
  depends_on "mpv" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.5/pikvm_0.3.5_darwin_x86_64.tar.gz"
      sha256 "11d66f4898551410aab1ccee9589fc212d52775f7ef60baa7c5fb8c7c8615bbe"

      define_method(:install) do
        bin.install "pikvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.5/pikvm_0.3.5_darwin_arm64.tar.gz"
      sha256 "2fbad1b2ac3dfd2d44baad6ad36d31c45d660c98d56e3191c35122167b155a3f"

      define_method(:install) do
        bin.install "pikvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.5/pikvm_0.3.5_linux_x86_64.tar.gz"
      sha256 "3563d0e471ebe866070b29a451a612eb51af11e41293dc1749ffbac82a6eb230"
      define_method(:install) do
        bin.install "pikvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/pikvm/releases/download/v0.3.5/pikvm_0.3.5_linux_arm64.tar.gz"
      sha256 "89548d90403e3cdb2f50958327329c3ea069761bf909399ff11fd723d9b32b9e"
      define_method(:install) do
        bin.install "pikvm"
      end
    end
  end

  test do
    assert_match "PiKVM Control", shell_output("#{bin}/pikvm --help")
  end
end
